### ISSUE TITLE
Achievements and stats are not saved

### ISSUE THREAD

**Issue by MeterPreter57** [MeterPreter57/MeterPreter57.github.io#7]
Steps to reproduce:
1. Start a new game in any mode on any map.
2. Survive for 1 minute or get an achievement (If you stand on one spot until your character dies you will get "Untouchable") and let the character die.
3. Return to the main menu.
4. No stats or achievements saved.

I tested in chrome in incognito mode and in normal mode (after deleting data). There are no errors in the console or network tab in devtools except for one that appears after you load the game.
```
[SW] Error writing cache entries:  DOMException: Cache.put() encountered a network error
    at https://meterpreter57.github.io/minidayz_1.4.1/sw.js:174:28
    at Array.map (<anonymous>)
    at https://meterpreter57.github.io/minidayz_1.4.1/sw.js:173:33
(anonymous) @ sw.js:181
Promise.catch (async)
(anonymous) @ sw.js:177
Promise.then (async)
CreateCacheFromFileList @ sw.js:148
(anonymous) @ sw.js:244
Promise.then (async)
(anonymous) @ sw.js:224
Promise.then (async)
(anonymous) @ sw.js:200
Promise.then (async)
UpdateCheck @ sw.js:193
(anonymous) @ sw.js:275

sw.js:265 [SW] Update check failed:  DOMException: Cache.put() encountered a network error
    at https://meterpreter57.github.io/minidayz_1.4.1/sw.js:174:28
    at Array.map (<anonymous>)
    at https://meterpreter57.github.io/minidayz_1.4.1/sw.js:173:33
(anonymous) @ sw.js:265
Promise.catch (async)
UpdateCheck @ sw.js:262
(anonymous) @ sw.js:275
```
I'll try to look into the code

**Comment by W84Soft** [comment]
It looks like the simulator is passing bad data after you save your achievements.

I wonder if this bug existed in the original version of the game because after refreshing the game page, the achievements load correctly.

**Comment by MeterPreter57** [comment]
Just tested and you are right, reloading the game loads stats and achievements. I think I should add the known issues section.
